### ISSUE TITLE
As a user, I want to be able to edit an absence by clicking on it in My Calendar and Team Calendar so that I can make changes

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#180]

**Comment by stevenhaynes** [comment]
Need's new UI for popup @robtulip  @natalietolley

**Comment by TheGarrett** [comment]
Are there AC's for this? So far I just have an input box on the pop-up when the holiday request is clicked

**Comment by TheGarrett** [comment]
Update: Now have it so when you view an absence, you click a button called 'Update'. Once button is clicked then the pop up changes to a pop-up similar to the 'Create Absence'. this is the way Natalie wanted it.

**Comment by KatherineGoldklang** [comment]
That sounds good Ryan

**Comment by KatherineGoldklang** [comment]
AC01 - Can I see a button which allows me to edit unconfirmed absences?
AC02 - When I click 'Edit' can I see a pop-up which allows me to edit my absence?
AC02 - When I have edited my absence, is it sent to my approver for approval?

**Comment by kieranmcnay** [comment]
Test 1

1. Launch and Login to the application.
2. Click on My Calendar.
3. Click on an Absence.

Failed. There's no Edit button when clicking on an absence.

Test 2

1. Launch and Login to the application.
2. Click on Team Calendar. 
3. Click on an Absence.

Failed. There's no Edit button when clicking on an absence.

**Comment by TheGarrett** [comment]
Code wasn't on dev server as Michael and John ran into problems

**Comment by AlexJYoungman** [comment]
Tested again.

1. Launch and Login to the application.
2. Click on My Calendar.
3. Click on an Absence.

Failed. Button is (mostly) hidden behind the [Close] button.

4. Opened Edit absence form

Failed. Overlapping absences feature doesn't work.
Also, duplicate values appear in the Absence Type dropdown.

5. Updated sickness to holiday

Passed. Value successfully taken from allowance.

Failed. Days left - Days Used = New balance not showing values correctly

Failed. Changing sickness to holiday allows me to go past 0 for my balance (E.g now i am on -3.5 holiday allowance)

Passed. Changing to an absence that requires approval successfully changed the state to pending so as not to circumvent approval.

**Comment by danieljtate** [comment]
Tested again

1. Launched app
2. Clicked on my Calendar
3. Selected an absence

Failed: On both pending and approved absences. 
- Absence balance does not update
- Overlapping absences do not work
-  Absence request still shows no matter what absence type is selected

4. Clicked submit

Passed/failed
- Serious bug where if a user clicks the "update" button several times before the modal closes it will reimburse the holidays incorrectly. For example you edit an absence from 1 day to 0.5 days but click update 6 times before the modal closes it will reimburse 3 full days rather than a half day.

5. Calendar updates correctly
6. Changing from sickness to holiday stops the user from exceeding their request

Overall. Failed test

**Comment by danieljtate** [comment]
Tested again

1. Launched app
2. Clicked on my Calendar
3. Selected an absence

On both pending and approved absences.

4. Absence balance updates
5. Overlapping  work
6. Balance disappears when not on holidays
7. Clicked submit
8. Calendar updates correctly
9. Changing from sickness to holiday stops the user from exceeding their request

[Passed]
