### ISSUE TITLE
As a team lead, I want to see the user page

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#24]
AC01: Can I see users listed?
AC02: Can I search and filter users?

**Comment by danieljtate** [comment]
Will make a start on this story and leave it within the product backlog until it has been story pointed

**Comment by danieljtate** [comment]
Created users table to list all users with their teams, projects and Role. The function bar along the top has been completed along with the modal views for each button and the search has been completed allowing you to search through the list based on name, teams and projects.  Working on the functionality for the checkboxes and the filter

**Comment by danieljtate** [comment]
Due to time constraints the filter button has been disabled and is hidden however the code is still there should we revisit. The ability to filter is within the search bar. If you type in a user,  team, project or role it will shorten the table based on what is typed into the box. Now just tidying up code to get it pushed up for review
